version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: "ruby"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-datapoint"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-enhance-k8s-metadata"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-events"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-metadata-filter"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-sumologic"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-prometheus-format"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-protobuf"
    ignore:
      - dependency-name: "fluentd"
    schedule:
      interval: "daily"
