version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: "ruby"
        versions:
          - "2.7.x"
          - "3.x"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-datapoint"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-enhance-k8s-metadata"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-events"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-metadata-filter"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-sumologic"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-prometheus-format"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-protobuf"
    ignore:
      - dependency-name: "google-protobuf"
    schedule:
      interval: "daily"
