version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-datapoint"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-enhance-k8s-metadata"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-events"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-metadata-filter"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-kubernetes-sumologic"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-prometheus-format"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"

  - package-ecosystem: "bundler"
    directory: "/fluent-plugin-protobuf"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"
