source 'https://rubygems.org'

gem 'kubeclient', git: 'https://github.com/ManageIQ/kubeclient', ref: '220b8d7af52180f9a0f69cb73f0723d2618cf3ef' 

gem 'codeclimate-test-reporter', '<2.0.0', :group => :test, :require => nil
gem 'rubocop', require: false

# Specify your gem's dependencies in fluent-plugin-add.gemspec
gemspec
