source 'https://rubygems.org'

gem 'kubeclient', git: 'https://github.com/abonas/kubeclient/', ref: '831e360772c717aab5ca086521c45c86ee51435e' 

gem 'codeclimate-test-reporter', '<2.0.0', :group => :test, :require => nil
gem 'rubocop', require: false

# Specify your gem's dependencies in fluent-plugin-add.gemspec
gemspec
