name: Dev builds

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build kubernetes-fluentd
        run: make build
      # We need to install awscli v1 via pip because it contains a version
      # that supports ecr-public while github actions environment on Ubuntu 20.04
      # contains aws v2.1.4 which doesn't know about it yet.
      # (support for ecr-public landed in v2.1.6)
      # ref: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
      - name: Install awscli
        run: |
          pip install awscli
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
      - name: Login to AWS public ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PUBLIC_ECR_SECRET_ACCESS_KEY }}
      - name: Push kubernetes-fluentd
        run: make push
