name: Dev builds

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Show Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to AWS public ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PUBLIC_ECR_SECRET_ACCESS_KEY }}

      - name: Build and push Debian image
        run: make build-push-multiplatform

      - name: Build and push Alpine image
        run: make build-push-multiplatform-alpine

      - name: Login to Open Source ECR
        run: make login-opensource
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OPENSOURCE_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OPENSOURCE_ECR_SECRET_ACCESS_KEY }}

      - name: Build and push Debian image to Open Source ECR
        run: make build-push-multiplatform-opensource

      - name: Build and push Alpine image to Open Source ECR
        run: make build-push-multiplatform-alpine-opensource
